// Generated by https://quicktype.io

export interface ProductResponse {
    id:          number;
    title:       string;
    price:       number;
    description: string;
    images:      string[];
    creationAt:  Date;
    updatedAt:   Date;
    category:    Category;
}

export interface Category {
    id:         number;
    name:       Name;
    image:      string;
    creationAt: Date;
    updatedAt:  Date;
}

export enum Name {
    Furniture = "Furniture",
    Miscellaneous = "Miscellaneous",
    Nuevo = "nuevo",
    Shoes = "Shoes",
}
